### ISSUE TITLE
RobinHood API Quote 

### ISSUE THREAD

**Issue by rwburke2** [codesociety/friartuck#10]
Anyone else having problems with the quotes from Robinhood.  I think it is their issue, but not positive.  Been getting:

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/UPRO/

**Comment by rwburke2** [comment]
Found this ->  I modified mine locally, will test tomorrow.

https://github.com/Jamonek/Robinhood/issues/167

**Comment by rwburke2** [comment]
Ok - - I modified my local code as suggested, and the quotes are now returning.  But now getting a pricing error when storing quotes from IEX which I've never seen.  Will create additional issue for that . . .

**Comment by codesociety** [comment]
Yes, Robinhood pulled the rug by making that update... I will take a look at the IEX issue, I was experiencing something similar. thanks for the finding...

**Comment by codesociety** [comment]
I believe this has been resolved, lets reopen if the problem returns
