### ISSUE TITLE
issue with cancel_order()

### ISSUE THREAD

**Issue by weiyiw0816** [codesociety/friartuck#4]
Hello,
I am afraid I do not know how to use cancel_order function. I tried the following and it seems it didn't work.
get_order_orders did return an object and cancel_order needs a str which is not what is returned by get_open_orders
    orderid = get_open_orders(security)
    cancel_order(orderid)

**Comment by codesociety** [comment]
hi weiyiw0816,

I believe the answer to you question is in the Readme page... however, it's possible that it's not clear enough:
when retrieving open orders for specific security, you will receive an array of order objects, you will need to loop through the array, identify the order you want to cancel and use the id of the order to cancel it.
Something like the following:

   # Retrieve all open orders by security
    open_orders = get_open_orders(security)
    for open_order in open_orders:
        log.info("AAPL open_order=%s" % open_order)
        cancel_order(open_order.id)
    
within the for loop, you may do some conditions on different properties of the order object (look at the readme file to see all the properties) to identify which order you would like to cancel... you may want to cancel all open orders, in that case the above sample code will do the trick.

Regards,

CodeSociety
