### ISSUE TITLE
Issue with context

### ISSUE THREAD

**Issue by pedroserano** [codesociety/friartuck#6]
I'm porting an algo from Quantopian, and I'm getting an error with 'context.output' but not sure what's causing it.

**Comment by codesociety** [comment]
Hi Pedroserano, as much as I wanted to replication Quantopian, I am afraid there's much that weren't implementated... I mainly focused on core functionality/structure and interaction with Robinhood... For me that's been working well... I am looking for more developers to come on board to help add more additional functionality... This may not help you at the moment, I will look into the context.ouput from Quantopian to see what it entails.

Regards,

Codesociety

**Comment by codesociety** [comment]
I've looked into the context.output quantopian, it is a variable that is set before trading starts and able to be used when trading starts... you can do the same by setting the variable in the initialize(context, data) or the on_market_open(context, data) functions and use it in the handle_data(context, data)... the problem could be that this usage is usually done when using pipe-line which not (yet) implemented. I am looking for more developers to join me and scale this project... Regards.
