### ISSUE TITLE
Google Prices

### ISSUE THREAD

**Issue by rwburke2** [codesociety/friartuck#7]
Hi - - Love this library btw.

Seems google has shut the pricing feed down.  Any thoughts on alternative pricing?

Thanks

**Comment by Darksaber501st** [comment]
I generally use IEX, it's fairly quick and simple.

**Comment by rwburke2** [comment]
Thanks @Darksaber501st  - have you integrated it into friartuck?

**Comment by Darksaber501st** [comment]
I did, but mostly just for testing purposea a while back. Simple URL calls for pricing, volume, etc, if you can code an algo for friartuck you should figure it out with ease. I also integrated a LOT of other things like logging algo actions and storing algo state variables in an ODBC database (MS ACCESS for me), a Web dashboard for the algo (I had others investing with me), and a few other things so my friartuck is a mess.

I haven't actively used friartuck in months, I had a lot of issues with Robinhood's API being crappy.and not handling calls right: orders being created but never actually placed, prices and other variables being off noticeably when compared to other sources, etc. I'm sticking with manual trading for now but TD Ameritrade recently redid their API and stopped requiring 500k to use it so I might go in that direction in the future

**Comment by rwburke2** [comment]
Thanks for the insight - - I've found using stop loss buys w/ RH and FT to be pretty effective.  Good luck going forward!

**Comment by codesociety** [comment]
Hi,
I am going to commit some changes before the week is over which integrates IEX (for historical data) and ALPHAVANTAGE for active day intraday data... IEX is has 1 month of intra-day  historical quotes but has a delay of 15 minutes for activeday quotes, (it does have live quotes which are traded in its systems, not comprehensive, for some symbols which not actively traded within IEX domain, you will see -1 for live quotes). Alphavantage does have live comprehensive quotes, however, it has a limitation of 5 queries per minute for free (has higher number of queries for premium).... I am testing the two combinations now with my algo, so far its going great....

**Comment by rwburke2** [comment]
Thanks @codesociety!!  Looking forward to it

**Comment by t-liv057** [comment]
@codesociety I'm just getting into algo trading and am super curious this repository.  If you need any help regarding the implementation of new data sources I'd love to lend a hand.  Currently implementing an iexfinance replacement for google finance.  I'm toying with quote_source.py and hope I'm starting in the right spot

**Comment by codesociety** [comment]
@t-liv057, yes quote_source is the Right spot... I really appreciate it.  I actually completed the implementation of the combination of iex and alpha vantage... Had a setback on Friday, made some adjustments over the weekend and I had a successful test today.... I am planning to commit the changes later tonight or tomorrow the latest... Thanks again

**Comment by t-liv057** [comment]
@codesociety That's great news!  I'll probably just wait for your commit to really start exploring, so I really appreciate it.  I found iex's api a little less versatile and I commend you for sorting it out.

**Comment by HyperionSounds** [comment]
@t-liv057 @codesociety @Darksaber501st @rwburke2 Thank you all. I have been following this thread, I am looking forward to checking out whatever you guys come up with! I have been struggling trying to get ib_insync and IBController to work in the mean time.

**Comment by codesociety** [comment]
@t-liv057 @codesociety @Darksaber501st @rwburke2 @HyperionSounds , I committed the changes yesterday, please read the commit message to help integrate the changes... you will need to install tinydb.
let me know if there are any questions

**Comment by rwburke2** [comment]
@codesociety Thanks for all the good work!  I have integrated the new code, but when I run it I am getting:
Traceback (most recent call last):
  File "friar_tuck_run.py", line 160, in <module>
    start_engine(sys.argv[1:])
  File "friar_tuck_run.py", line 137, in start_engine
    friar_tuck = FriarTuckLive(user_name=config.get('LOGIN', 'username'), password=config.get('LOGIN', 'password'), data_frequency=data_frequency)
TypeError: __init__() got an unexpected keyword argument 'user_name'

If I change friar_tuck_run.py, line 137 from user_name, to username I get:

Traceback (most recent call last):
  File "friar_tuck_run.py", line 160, in <module>
    start_engine(sys.argv[1:])
  File "friar_tuck_run.py", line 137, in start_engine
    friar_tuck = FriarTuckLive(username=config.get('LOGIN', 'username'), password=config.get('LOGIN', 'password'), data_frequency=data_frequency)
TypeError: __init__() got an unexpected keyword argument 'password'

From here I've been stuck . . . 

Any pointers appreciated

**Comment by codesociety** [comment]
I am sure it something I didn't commit... I'll check and resolve later today.

**Comment by codesociety** [comment]
Found the issue and resolved it... please see the last commit and try it...

**Comment by rwburke2** [comment]
so far so good!

**Comment by rwburke2** [comment]
also needed to add a data subdir in algo root for IEX/tinydb, off and running now.  Thanks again!

**Comment by rwburke2** [comment]
looks like multiple security lookups is not working, ie
    # Get field(s) for more than 1 security
    current_quote = data.current([context.aapl, context.wtw], field='close')
    log.debug(current_quote)
or maybe I'm doing it wrong with the new implementation? or need to implement BATCH_QUOTES_US function for alpha?

**Comment by codesociety** [comment]
I actually wish that we could use batch quotes, however, it is not for timeseries quotes (1min, 5min...). Thanks for bringing up the issue, should be something minor, I will look into it some time tomorrow, hoping early.

**Comment by codesociety** [comment]
@rwburke2 issue resolved... please check it out... again thanks for finding it and bringing it up.

**Comment by rwburke2** [comment]
Looking good!  Appreciate it!
